---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: db
    version: "8.0"
spec:
  containers:
    - name: mysqldb
      image: mysql:8.0
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: openmrs
        - name: MYSQL_USER
          value: DB_USR1
        - name: MYSQL_PASSWORD
          value: P@ssword
