---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs-deploy-pod
spec:
  minReadySeconds: 30
  replicas: 3
  selector:
    matchLabels:
      app: openmrs
  strategy:
    rollingUpdate:
      maxSurge: 45%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      containers:
        - name: openmrs
          image: sukhenzie/openmrs:1.0
          ports:
            - containerPort: 49153
              protocol: TCP
