---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openmrs-rc
  labels:
    app: openmrs
spec:
  replicas: 3
  selector:
    app: openmrs
    version: "1.0"
  template:
    metadata:
      labels:
        app: openmrs
        version: "1.0"
    spec:
      containers:
        - name: openmrs
          image: sukhenzie/openmrs:1.0
          ports:
            - containerPort: 49153
              protocol: TCP
