---
apiVersion: v1
kind: Pod
metadata: 
  name: openmrs
  labels:
    app: openmrs
    version: "1.0"
spec:
  containers:
    - name: openmrs
      image: sukhenzie/openmrs:1.0
      ports:
        - containerPort: 49153
          protocol: TCP
